# Generated by Django 4.2.2 on 2023-08-11 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(default="P", max_length=1)),
                ("position_x", models.PositiveIntegerField()),
                ("position_y", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="table", max_length=50, null=True
                    ),
                ),
                ("position_x", models.FloatField()),
                ("position_y", models.FloatField()),
                ("type", models.CharField(default="T", max_length=1)),
                ("is_occupied", models.BooleanField(default=False)),
                (
                    "plates",
                    models.ManyToManyField(
                        blank=True, related_name="tables", to="table.plate"
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table.restaurant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plate",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="table.restaurant"
            ),
        ),
        migrations.AddField(
            model_name="plate",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="table.table"
            ),
        ),
    ]
